import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `vitest --coverage`. Already in .gitignore, but the
    // ESLint CLI still walks the directory and lints the v8 reporter's
    // bundled helper files (block-navigation.js etc.) if they're present.
    "coverage/**",
  ]),
]);

export default eslintConfig;
