"""add_price_estimates_table

Revision ID: 8bda05408c97
Revises: b3a1c9d2e4f5
Create Date: 2026-05-04 02:03:11.929894
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '8bda05408c97'
down_revision: str | None = 'b3a1c9d2e4f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('model_type', sa.String(length=30), nullable=False),
    sa.Column('cheap_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('fair_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('expensive_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', 'model_type', name='uq_price_estimates_stock_date_model')
    )
    op.create_index('ix_price_estimates_stock_date', 'price_estimates', ['stock_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_estimates_stock_date', table_name='price_estimates')
    op.drop_table('price_estimates')
    # ### end Alembic commands ###
