"""add_industry_metrics_table

Revision ID: e900cd627d8a
Revises: af683002958e
Create Date: 2026-05-06 04:12:23.445997
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'e900cd627d8a'
down_revision: str | None = 'af683002958e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('median_pe', sa.Float(), nullable=True),
    sa.Column('median_pb', sa.Float(), nullable=True),
    sa.Column('median_yield', sa.Float(), nullable=True),
    sa.Column('median_gross_margin', sa.Float(), nullable=True),
    sa.Column('median_operating_margin', sa.Float(), nullable=True),
    sa.Column('median_net_margin', sa.Float(), nullable=True),
    sa.Column('median_roe', sa.Float(), nullable=True),
    sa.Column('median_roa', sa.Float(), nullable=True),
    sa.Column('median_revenue_growth_yoy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_metrics_industry_id'), 'industry_metrics', ['industry_id'], unique=False)
    op.create_index(op.f('ix_industry_metrics_period'), 'industry_metrics', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_industry_metrics_period'), table_name='industry_metrics')
    op.drop_index(op.f('ix_industry_metrics_industry_id'), table_name='industry_metrics')
    op.drop_table('industry_metrics')
    # ### end Alembic commands ###
